const SCALE_STEP = 25;
const SCALE_MAX = 100;
const SCALE_MIN = 25;
const MAX_HASHTAGS_QUANTITY = 5;
const RANDOM_PHOTOS_QUANTITY = 10;
const FILTER_DELAY = 500;
const COMMENTS_QUANTITY_STEP = 5;
const TOTAL_COMMENTS_QUANTITY_INDEX = 2;
const CURRENT_COMMENTS_QUANTITY_INDEX = 0;
const SERVER_SEND_ADRESS = 'https://22.javascript.pages.academy/kekstagram';
const SERVER_GET_ADRESS = 'https://22.javascript.pages.academy/kekstagram/data';
const FILE_TYPES = ['gif', 'jpg', 'jpeg', 'png'];

export {FILE_TYPES, CURRENT_COMMENTS_QUANTITY_INDEX ,TOTAL_COMMENTS_QUANTITY_INDEX ,COMMENTS_QUANTITY_STEP ,FILTER_DELAY ,RANDOM_PHOTOS_QUANTITY, SERVER_SEND_ADRESS, SERVER_GET_ADRESS, MAX_HASHTAGS_QUANTITY, SCALE_STEP, SCALE_MAX, SCALE_MIN};
